# Generated by Django 5.1.6 on 2025-03-12 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0002_taskers_alter_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todolistapp.taskers'),
        ),
    ]
